books/urls.py
from django.urls import path
from .views import books_list

urlpatterns = [
    path('',books_list),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from main.views import hello_world,about_page

app_name = 'main'

urlpatterns = [
    path('', hello_world,name='home_page'),
    path('about', about_page,name='about_page'),
]

posts/urls.py
from django.urls import path
from .views import posts_list,post_details

app_name = 'posts'

urlpatterns = [
    path('',posts_list,name='list'),
    path('<int:post_id>', post_details,name='details'),
]

pywww/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('', include('main.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    #tytuł książki
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=50)
    description = models.TextField()
    available = models.BooleanField()
    publication_year = models.IntegerField()

    def __str__(self):
        return f'{self.title}: {self.author}'

main/models.py
from django.db import models

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField("auth.User",on_delete=models.CASCADE)
    bio = models.TextField()

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Posts(models.Model):
    #tytuł o max. długości 255 znaków
    title = models.CharField(max_length=255)

    #pole tekstowe o nieokreślonej długości
    content = models.TextField()

    #flaga true/false
    published = models.BooleanField(default=False)

    #data publikacji
    created = models.DateTimeField(auto_now_add=True)

    #data ostatniej modyfikacji
    modified = models.DateTimeField(auto_now=True)

    #
    sponsored = models.BooleanField(default=False)

    #FOREIGN KEY TO USER that made a post
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,related_name="posts")


    def __str__(self):
        return f'{self.id} {self.title}'

tags/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
    name = models.CharField(unique=True,max_length=255)
    slug = models.SlugField(unique=True,max_length=255)

books/views.py
from django.shortcuts import render
from django.template import loader
from .models import Book

# Create your views here.
def books_list(request):
    books_list = Book.objects.all()
    context = {'books': books_list}
    return render(request,"books/books_list.html",context)

main/views.py
#from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def hello_world(request):
    return render(request,'main/home_page.html',{})

def about_page(request):
    return render(request,'main/about.html',{})

posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from posts.models import Posts
from django.template import loader
from django.shortcuts import render
# Create your views here.

def post_details(request,post_id):
    post = Posts.objects.get(pk=post_id)
    return render(request,"posts/details.html",{'post':post})

def posts_list(request):
    posts = Posts.objects.all()
    context = {'posts': posts}
    return render(request,"posts/list.html",context)

tags/views.py
from django.shortcuts import render

# Create your views here.

books/templates/books/book_add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

books/templates/books/book_details.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

books/templates/books/book_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

books/templates/books/book_rent.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

books/templates/books/books_list.html
{% extends "C:\Users\Karol\Desktop\pywww\pywww\posts\templates\posts\base.html" %}
{% block content %}
    <h1>Lista książek</h1>
    <table>
        <tr>
            <th>Autor</th>
            <th>Tytył</th>
            <th>Dostępność</th>
        </tr>
        {% for book in books %}
            <tr>
                <td>{{ book.author }}</td>
                <td>{{ book.title }}</td>
                {% if book.available %}
                    <td> Na półce </td>
                {% else %}
                    <td>Wypożyczona</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{%endblock%}

books/templates/books/books_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

books/templates/books/rent_list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

main/templates/main/about.html
{%extends "main/base.html"%}
{% block content %}
    <h1>O projekcie</h1>
    <p>Nauka Django poprzez praktykę :)</p>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}<title>Bazowy html</title>{% endblock %}
    <link href="{% static "main/css/style.css" %}" rel="stylesheet">
    {% block styles %} {%endblock%}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    {% block header%}
    <div class="container">
        <header class="d-flex justify-content-center py-3">
          <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'main:home_page' %}" class="nav-link active" aria-current="page">Home Page</a></li>
            <li class="nav-item"><a href="{% url 'posts:list' %}" class="nav-link" aria-current="page">Posts list</a></li>
            <li class="nav-item"><a href="{% url 'main:about_page' %}" class="nav-link">About</a></li>
          </ul>
        </header>
    </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</body>
</html>

main/templates/main/home_page.html
{%extends "main/base.html"%}
{% load static %}

{% block content %}
    <img src="{% static 'main/img/blog_img.jpg' %}">
{% endblock %}
{% block footer %}
    <p>&copy KK</p>
{% endblock %}

posts/templates/posts/add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

posts/templates/posts/add1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bazowy html</title>
</head>
<body>
{% block header%}
    <header>
        <h1>To jest header</h1>
        <a href="{% url 'main:home_page' %}">Home Page</a>
    </header>
{% endblock %}
{% block content %}
{% endblock %}
{% block footer %}
{% endblock %}
</body>
</html>

posts/templates/posts/details.html
{% extends "posts/base.html" %}
{% block content %}
    {% load posts_extras %}
        <h1>Details about posts</h1>
        Title: {{ post.title }} </br>
        Signs: {% count_signs post.content %} </br>
        Words: {% count_words post.content %} </br>
        Added: {{post.created|date:"D, d M Y"}} </br></br>
        {% if post.sponsored %}
            THIS POST IS SPONSORED BY ...
        {% endif %}
        </br>
        <a href="{% url 'posts:list' %}">Go back to psots list page</a>
{% endblock %}

posts/templates/posts/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

posts/templates/posts/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Tutaj będzie biblioteka</h1>
<small>Utworzono {{ post.created }}, zmodyfikowano {{ post.modified }}</small>
<p>{{ post.content }}</p>
<p>Ocena kursu: {{ile}}</p>
</body>
</html>

posts/templates/posts/list.html
{% extends "posts/base.html" %}
{% block content %}
<div class="list container">
    <ul class="list-group list-group-unnumbered">
        {% for post in posts %}
            <li class="list-group-item"><a href="{% url 'posts:details' post.id %}" >{{post}}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

pywww/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

register/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>